thesis:
  scenarioid: 'York-Fedora-Thesis-Object'
  parentcollection: 'york:3'
  submittedBy: fedoraAdmin
  client: ThesisClient
  stopOnError: false
  accesskey: <%= ENV['DEV.WORKFLOW_API_KEY'] %>
  tmpfilepath: /public/uploadedfiles/
  tmpfileurl:  /uploadedfiles/
image:
  scenarioid: 'York-Fedora-StillImage-Object'
filestore:
  yodlprodingest: 'tmpdata/'
  archbishop: 'tmpdata/'
tmppath: 'tmpdata_output/'

