# server: 'https://yodlapp3.york.ac.uk'
server: 'https://dlib.york.ac.uk'
thesis:
  scenarioid: 'York-Fedora-Thesis-Object'
  parentcollection: 'york:847875'
  submittedBy: fedoraAdmin
  client: ThesisClient
  stopOnError: false
  accesskey: <%= ENV['LIVE.WORKFLOW_API_KEY'] %>
  tmpfilepath: /public/uploadedfiles/
  tmpfileurl:  /uploadedfiles/
filestore:
  yodlprodingest: '/usr/digilib-ingest/'
  archbishop: '/usr/digilib-archbishop/'
tmppath: '/tmp/'
batch:
  parentcollection: 'york:855395'
  #parentcollection: 'york:8329486'
