thesis:
  scenarioid: 'York-Fedora-Thesis-Object'
  parentcollection: 'york:847875'
  submittedBy: fedoraAdmin
  client: ThesisClient
  stopOnError: false
  accesskey: <%= ENV['TEST.WORKFLOW_API_KEY'] %>
